name: bf_control_centre
description: "Control Centre of BillingFast"
publish_to: "none"

version: 4.0.0+400

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  gap: ^3.0.1
  shared_preferences: ^2.5.3
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  pdf: ^3.11.3
  intl: ^0.20.2
  printing: ^5.14.2
  csv: ^6.0.0
  file_saver: ^0.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
